# Generated by Django 3.0.5 on 2020-04-24 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'accessories',
            },
        ),
        migrations.CreateModel(
            name='AccessoryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'accessorycategories',
            },
        ),
        migrations.CreateModel(
            name='Caliper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'calipers',
            },
        ),
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'carpets',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='CustomCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'customcars',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code1', models.CharField(max_length=100)),
                ('code2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dashboards',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0)),
                ('width_side', models.IntegerField(default=0)),
                ('width_noside', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('wheelbase', models.IntegerField(default=0)),
                ('front_track', models.IntegerField(default=0)),
                ('rear_track', models.IntegerField(default=0)),
                ('front_overhang', models.IntegerField(default=0)),
                ('rear_overhang', models.IntegerField(default=0)),
                ('turning_circle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boot_capacity', models.IntegerField(default=0)),
                ('fuel_tank_capacity', models.IntegerField(default=0)),
                ('unladen_weight', models.IntegerField(default=0)),
                ('kerb_weight', models.IntegerField(default=0)),
                ('tire_size_front', models.CharField(max_length=50)),
                ('tire_size_back', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dimensions',
            },
        ),
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'exteriors',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lines',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='ModelVersionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Dimension')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Line')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Model')),
            ],
            options={
                'db_table': 'model_version_lines',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('list1', models.CharField(max_length=500)),
                ('list2', models.CharField(max_length=500)),
                ('list3', models.CharField(max_length=500)),
                ('list4', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceleration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_speed', models.IntegerField(default=0)),
                ('displacement', models.IntegerField(default=0)),
                ('max_torque', models.IntegerField(default=0)),
                ('max_power', models.IntegerField(default=0)),
                ('engine_layout', models.CharField(max_length=50)),
                ('engine_stroke', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'specs',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'versions',
            },
        ),
        migrations.CreateModel(
            name='WheelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumnail_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'wheeltypes',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('model_version_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine')),
                ('wheel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.WheelType')),
            ],
            options={
                'db_table': 'wheels',
            },
        ),
        migrations.CreateModel(
            name='SteeringType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumnail_url', models.URLField(max_length=2000)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Steering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('dashboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Dashboard')),
                ('steering_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.SteeringType')),
            ],
            options={
                'db_table': 'steerings',
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumnail_url', models.URLField(max_length=2000)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Color')),
            ],
            options={
                'db_table': 'seattypes',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('model_version_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine')),
                ('seat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.SeatType')),
            ],
            options={
                'db_table': 'seats',
            },
        ),
        migrations.CreateModel(
            name='ModelVersionLinePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CustomCar')),
                ('model_version_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Package')),
            ],
            options={
                'db_table': 'modelversionlinepackages',
            },
        ),
        migrations.AddField(
            model_name='modelversionline',
            name='sepc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Spec'),
        ),
        migrations.AddField(
            model_name='modelversionline',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Version'),
        ),
        migrations.CreateModel(
            name='InteriorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Carpet')),
                ('dashboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Dashboard')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Seat')),
                ('steering', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Steering')),
            ],
            options={
                'db_table': 'interiorgroups',
            },
        ),
        migrations.CreateModel(
            name='ExteriorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumnail_url', models.URLField(max_length=2000)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Color')),
            ],
            options={
                'db_table': 'exteriortypes',
            },
        ),
        migrations.CreateModel(
            name='ExteriorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caliper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Caliper')),
                ('exterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Exterior')),
                ('wheel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Wheel')),
            ],
            options={
                'db_table': 'exteriorgroups',
            },
        ),
        migrations.AddField(
            model_name='exterior',
            name='exterior_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ExteriorType'),
        ),
        migrations.AddField(
            model_name='exterior',
            name='model_version_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine'),
        ),
        migrations.CreateModel(
            name='DashboardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumnail_url', models.URLField(max_length=2000)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Color')),
            ],
            options={
                'db_table': 'dashboardtypes',
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='dashboard_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.DashboardType'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Seat'),
        ),
        migrations.CreateModel(
            name='CustomCarProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('code', models.CharField(max_length=400)),
                ('custom_car', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CustomCar')),
            ],
            options={
                'db_table': 'customcarprofiles',
            },
        ),
        migrations.CreateModel(
            name='CustomCarAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('accessory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Accessory')),
                ('custom_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CustomCar')),
            ],
            options={
                'db_table': 'customcaraccessories',
            },
        ),
        migrations.AddField(
            model_name='customcar',
            name='customcar_accessory',
            field=models.ManyToManyField(through='car.CustomCarAccessory', to='car.Accessory'),
        ),
        migrations.AddField(
            model_name='customcar',
            name='exterior_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ExteriorGroup'),
        ),
        migrations.AddField(
            model_name='customcar',
            name='interior_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.InteriorGroup'),
        ),
        migrations.AddField(
            model_name='customcar',
            name='model_version_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine'),
        ),
        migrations.AddField(
            model_name='customcar',
            name='package',
            field=models.ManyToManyField(through='car.ModelVersionLinePackage', to='car.Package'),
        ),
        migrations.CreateModel(
            name='CarpetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumnail_url', models.URLField(max_length=2000)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Color')),
            ],
            options={
                'db_table': 'carpettypes',
            },
        ),
        migrations.AddField(
            model_name='carpet',
            name='carpet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CarpetType'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='dashboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Dashboard'),
        ),
        migrations.CreateModel(
            name='CaliperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumnail_url', models.URLField(max_length=2000)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Color')),
            ],
            options={
                'db_table': 'calipertypes',
            },
        ),
        migrations.AddField(
            model_name='caliper',
            name='caliper_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CaliperType'),
        ),
        migrations.AddField(
            model_name='caliper',
            name='model_version_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.AccessoryCategory'),
        ),
    ]
