# Generated by Django 3.0.5 on 2020-04-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'accessories',
            },
        ),
        migrations.CreateModel(
            name='AccessoryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'accessory_categories',
            },
        ),
        migrations.CreateModel(
            name='Caliper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'calipers',
            },
        ),
        migrations.CreateModel(
            name='CaliperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'caliper_types',
            },
        ),
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'carpets',
            },
        ),
        migrations.CreateModel(
            name='CarpetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'carpet_types',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='ColorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'color_types',
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.BooleanField()),
                ('call', models.BooleanField()),
                ('sns', models.BooleanField()),
                ('sms', models.BooleanField()),
                ('fax', models.BooleanField()),
                ('email', models.BooleanField()),
            ],
            options={
                'db_table': 'custom_channels',
            },
        ),
        migrations.CreateModel(
            name='CustomCarAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('accessory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Accessory')),
            ],
            options={
                'db_table': 'custom_car_accessories',
            },
        ),
        migrations.CreateModel(
            name='CustomCarOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customcar_accessory', models.ManyToManyField(through='car.CustomCarAccessory', to='car.Accessory')),
            ],
            options={
                'db_table': 'custom_car_options',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code1', models.CharField(max_length=100)),
                ('code2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dashboards',
            },
        ),
        migrations.CreateModel(
            name='DashboardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.URLField(max_length=2000)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Color')),
            ],
            options={
                'db_table': 'dashboard_types',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0)),
                ('width_side', models.IntegerField(default=0)),
                ('width_noside', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('wheelbase', models.IntegerField(default=0)),
                ('front_track', models.IntegerField(default=0)),
                ('rear_track', models.IntegerField(default=0)),
                ('front_overhang', models.IntegerField(default=0)),
                ('rear_overhang', models.IntegerField(default=0)),
                ('turning_circle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boot_capacity', models.IntegerField(default=0)),
                ('fuel_tank_capacity', models.IntegerField(default=0)),
                ('unladen_weight', models.IntegerField(default=0)),
                ('kerb_weight', models.IntegerField(default=0)),
                ('tire_size_front', models.CharField(max_length=50)),
                ('tire_size_back', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dimensions',
            },
        ),
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'exteriors',
            },
        ),
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'image_urls',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lines',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='ModelVersionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=400)),
                ('dimension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Dimension')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Line')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Model')),
            ],
            options={
                'db_table': 'model_version_lines',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('description_list', models.TextField()),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceleration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_speed', models.IntegerField(default=0)),
                ('displacement', models.IntegerField(default=0)),
                ('max_torque', models.IntegerField(default=0)),
                ('max_power', models.IntegerField(default=0)),
                ('engine_layout', models.CharField(max_length=50)),
                ('engine_bore', models.DecimalField(decimal_places=2, max_digits=10)),
                ('engine_stroke', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'specs',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'versions',
            },
        ),
        migrations.CreateModel(
            name='WheelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'wheel_types',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('model_version_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine')),
                ('wheel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.WheelType')),
            ],
            options={
                'db_table': 'wheels',
            },
        ),
        migrations.CreateModel(
            name='SteeringType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.URLField(max_length=2000)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Color')),
            ],
            options={
                'db_table': 'steering_types',
            },
        ),
        migrations.CreateModel(
            name='Steering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('dashboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Dashboard')),
                ('steering_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.SteeringType')),
            ],
            options={
                'db_table': 'steerings',
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.URLField(max_length=2000)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Color')),
            ],
            options={
                'db_table': 'seat_types',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code1', models.CharField(max_length=100)),
                ('code2', models.CharField(max_length=100)),
                ('model_version_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine')),
                ('seat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.SeatType')),
            ],
            options={
                'db_table': 'seats',
            },
        ),
        migrations.CreateModel(
            name='PackageCustomCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_car_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CustomCarOption')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Package')),
            ],
            options={
                'db_table': 'package_custom_cars',
            },
        ),
        migrations.CreateModel(
            name='ModelVersionLinePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Package')),
            ],
            options={
                'db_table': 'model_version_line_packages',
            },
        ),
        migrations.AddField(
            model_name='modelversionline',
            name='spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Spec'),
        ),
        migrations.AddField(
            model_name='modelversionline',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Version'),
        ),
        migrations.CreateModel(
            name='InteriorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Carpet')),
                ('dashboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Dashboard')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Seat')),
                ('steering', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Steering')),
            ],
            options={
                'db_table': 'interior_groups',
            },
        ),
        migrations.CreateModel(
            name='ExteriorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.URLField(max_length=2000)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Color')),
                ('color_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ColorType')),
            ],
            options={
                'db_table': 'exterior_types',
            },
        ),
        migrations.CreateModel(
            name='ExteriorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caliper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Caliper')),
                ('exterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Exterior')),
                ('wheel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Wheel')),
            ],
            options={
                'db_table': 'exterior_groups',
            },
        ),
        migrations.AddField(
            model_name='exterior',
            name='exterior_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ExteriorType'),
        ),
        migrations.AddField(
            model_name='exterior',
            name='model_version_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine'),
        ),
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caliper_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CaliperType')),
                ('carpet_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CarpetType')),
                ('dashboard_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.DashboardType')),
                ('exterior_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ExteriorType')),
                ('model_version_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine')),
                ('seat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.SeatType')),
                ('steering_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.SteeringType')),
                ('wheel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.WheelType')),
            ],
            options={
                'db_table': 'defaults',
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='dashboard_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.DashboardType'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Seat'),
        ),
        migrations.AddField(
            model_name='customcaroption',
            name='exterior_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ExteriorGroup'),
        ),
        migrations.AddField(
            model_name='customcaroption',
            name='interior_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.InteriorGroup'),
        ),
        migrations.AddField(
            model_name='customcaroption',
            name='model_version_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine'),
        ),
        migrations.AddField(
            model_name='customcaroption',
            name='package',
            field=models.ManyToManyField(through='car.PackageCustomCar', to='car.Package'),
        ),
        migrations.AddField(
            model_name='customcaraccessory',
            name='custom_car_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CustomCarOption'),
        ),
        migrations.CreateModel(
            name='CustomCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('code', models.CharField(max_length=400)),
                ('privacy_check', models.BooleanField()),
                ('contact_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ContactChannel')),
                ('custom_car_option', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CustomCarOption')),
            ],
            options={
                'db_table': 'custom_cars',
            },
        ),
        migrations.AddField(
            model_name='carpettype',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Color'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='carpet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CarpetType'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='dashboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Dashboard'),
        ),
        migrations.AddField(
            model_name='calipertype',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.Color'),
        ),
        migrations.AddField(
            model_name='caliper',
            name='caliper_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CaliperType'),
        ),
        migrations.AddField(
            model_name='caliper',
            name='model_version_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='accessory_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.AccessoryCategory'),
        ),
    ]
