# Generated by Django 3.0.5 on 2020-04-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_colortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='exteriortype',
            name='color_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ColorType'),
        ),
    ]
