# Generated by Django 3.0.5 on 2020-04-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_exteriortype_color_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='thumbnail_url',
            field=models.URLField(default=None, max_length=2000),
            preserve_default=False,
        ),
    ]
