# Generated by Django 3.0.5 on 2020-04-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_accessory_thumbnail_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='category',
            new_name='accessory_category',
        ),
    ]
