# Generated by Django 3.0.5 on 2020-04-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20200427_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='code',
            new_name='code1',
        ),
        migrations.AddField(
            model_name='modelversionline',
            name='code',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='code2',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
