# Generated by Django 3.0.5 on 2020-04-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20200427_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelversionline',
            name='code',
            field=models.CharField(max_length=400),
        ),
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caliper_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CaliperType')),
                ('carpet_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.CarpetType')),
                ('dashboard_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.DashboardType')),
                ('exterior_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ExteriorType')),
                ('model_version_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.ModelVersionLine')),
                ('seat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.SeatType')),
                ('steering_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.SteeringType')),
                ('wheel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.WheelType')),
            ],
            options={
                'db_table': 'defaults',
            },
        ),
    ]
