# Generated by Django 3.0.5 on 2020-04-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20200427_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'image_urls',
            },
        ),
    ]
