# Generated by Django 3.0.5 on 2020-04-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageurl',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
