# Generated by Django 3.0.5 on 2020-04-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeinformation',
            old_name='exhibition_cneter',
            new_name='exhibition_center',
        ),
    ]
