# Generated by Django 3.0.5 on 2020-04-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20200426_1240'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='storeinformation',
            table='store_informations',
        ),
    ]
