# Generated by Django 3.0.5 on 2020-04-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20200426_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveContactChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BooleanField()),
                ('fax', models.BooleanField()),
                ('mail', models.BooleanField()),
                ('sms', models.BooleanField()),
                ('call', models.BooleanField()),
                ('sns', models.BooleanField()),
            ],
            options={
                'db_table': 'drive_contact_channels',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_check',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='drive_contact_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.DriveContactChannel'),
        ),
    ]
