# Generated by Django 3.0.5 on 2020-04-30 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20200429_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.AddressCity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.Gender'),
        ),
        migrations.AlterModelTable(
            name='addresscity',
            table='address_cities',
        ),
    ]
